project_id = "zpsaqbedoejdozimzdsp"

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.cash-out]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-gift-recipient]
verify_jwt = true
